---
title: "All Entries Descriptives"
output:
  html_document:
    keep_md: yes
    toc: yes
  pdf_document: default
---


```{r, results="asis", echo=FALSE, message=FALSE}
source('../RCode/Download and Clean PT Data.R')
source('../RCode/PT Analysis.R')
```

### TOTAL NUMBER OF ARTICLES: `r nrow(Private)`

```{r, results="asis", echo=FALSE, message=FALSE}
DataSet1 <- PrivatePubLangLabel
GraphName1 <- "All Entries"

PrivatePubLangGraph <- ggplot(data=DataSet1, aes(x=x, y=Freq)) + geom_bar(stat="identity") + ggtitle(GraphName1) +
  geom_text(size=3, data=DataSet1,aes(x=x,y=Freq,label=lab),hjust=-.1) +
  theme(axis.title.x=element_blank(), axis.title.y=element_blank(), panel.background=element_blank(), plot.title=element_text(size=10)) + 
  scale_y_continuous(limits = c(0, 350)) + coord_flip()

DataSet1 <- AllAsiaPubLangLabel
GraphName1 <- "Asia Regions"

AllAsiaPubLangGraph <- ggplot(data=DataSet1, aes(x=x, y=Freq)) + geom_bar(stat="identity") + ggtitle(GraphName1) +
  geom_text(size=3, data=DataSet1,aes(x=x,y=Freq,label=lab),hjust=-.1) +
  theme(axis.title.x=element_blank(), axis.title.y=element_blank(), panel.background=element_blank(), plot.title=element_text(size=10)) + 
  scale_y_continuous(limits = c(0, 350)) + coord_flip()

grid.arrange(PrivatePubLangGraph, AllAsiaPubLangGraph, ncol=2)
```

